name: Bug Report
description: File a bug report
title: "[Bug]: "
labels: ["bug"]
assignees: ''
body:
  - type: markdown
    attributes:
      value: |
        Please note: you are filing a report for the ***non*** Add-On version. If you want to file a report for the miscale Home Assistant Add-On, please click [here](https://github.com/lolouk44/hassio-addons/issues/new?assignees=&labels=bug&template=bug_report.yml&title=%5BBug%5D%3A+)
  - type: textarea
    id: bug-description
    attributes:
      label: Describe the bug
      description: Clear and concise description of what the bug is
      placeholder: Explain what you see.
    validations:
      required: true
  - type: textarea
    id: reproduction-steps
    attributes:
      label: To Reproduce
      description: Steps to reproduce the behaviour, including error message if any.
      placeholder: Explain how/when it happens.
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell
  - type: textarea
    id: expected-behaviour
    attributes:
      label: Expected behaviour
      description: A clear and concise description of what you expected to happen.
      placeholder: Explain what should happenTell us what you see!
  - type: input
    id: scale-info
    attributes:
      label: Scale
      description: Please provide scale name and model.
      placeholder: Example Mi Scale V2 XMTZCO1HM
    validations:
      required: true
  - type: dropdown
    id: installation
    attributes:
      label: Installation
      description: How is the miscale installed and running?
      options:
        - Docker
        - Github Clone
    validations:
      required: true
  - type: dropdown
    id: computer
    attributes:
      label: Device used to run the Script/Container
      description: What device does this program runs on?
      options:
        - Computer/Laptop
        - Raspberry Pi
    validations:
      required: true
  - type: dropdown
    id: bluetooth
    attributes:
      label: Bluetooth
      description: Which bluetooth radio is used?
      options:
        - Built-In
        - USB Dongle
    validations:
      required: true
  - type: textarea
    id: additional-info
    attributes:
      label: Additional Info
      description: Add any other info relevant to the problem here.
